// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OverTheTop.Infrastructure.Data;

#nullable disable

namespace OverTheTop.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503191528_AddUserSettings")]
    partial class AddUserSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OverTheTop.Domain.Entities.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Club")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PreferredHand")
                        .HasColumnType("integer");

                    b.Property<int?>("PreferredStyle")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.Property<int?>("WeightCategory")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.DayTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<Guid>("MesocycleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MesocycleId");

                    b.ToTable("DayTemplates");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLibrary")
                        .HasColumnType("boolean");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Style")
                        .HasColumnType("integer");

                    b.Property<string>("Tips")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Повільне обертання зап'ястка досередини з гантеллю або лямкою. Основний рух топ-ролу.",
                            IsLibrary = true,
                            MuscleGroup = 0,
                            Name = "Пронація зап'ястка",
                            NameEn = "Wrist Pronation",
                            Style = 0,
                            Tips = "Тримай лікоть нерухомо. Фокус на крайній точці пронації."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Тяга лямки або блоку лише силою пальців без участі зап'ястка.",
                            IsLibrary = true,
                            MuscleGroup = 1,
                            Name = "Тяга пальцями",
                            NameEn = "Finger Pull",
                            Style = 0,
                            Tips = "Не стискай в кулак — тяни кінчиками. Зміцнює захват для відкату пальців суперника."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Розгинання зап'ястка назад з опором — фінальна фаза руху топ-ролу.",
                            IsLibrary = true,
                            MuscleGroup = 0,
                            Name = "Скрут зап'ястка назовні",
                            NameEn = "Wrist Roll Out",
                            Style = 0,
                            Tips = "Зосередься на повільному ексцентрику. Не перекидай зап'ясток."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Утримання супінованого зап'ястка з лямкою на блоці під різними кутами.",
                            IsLibrary = true,
                            MuscleGroup = 0,
                            Name = "Кубок",
                            NameEn = "Cup Exercise",
                            Style = 1,
                            Tips = "Стискай максимально і утримуй. Ключова вправа для фінальної позиції хука."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Обертання зап'ястка назовні з опором — основний рух хука.",
                            IsLibrary = true,
                            MuscleGroup = 0,
                            Name = "Супінація зап'ястка",
                            NameEn = "Wrist Supination",
                            Style = 1,
                            Tips = "Поєднуй з тягою ліктя всередину для повної симуляції хука."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Тяга блоку з лямкою в супінованому положенні — максимальна симуляція хука.",
                            IsLibrary = true,
                            MuscleGroup = 1,
                            Name = "Тяга ременя на хук",
                            NameEn = "Hook Strap Pull",
                            Style = 1,
                            Tips = "Тримай зап'ясток зігнутим до себе під час тяги."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Рух плечем назад і всередину — повернення з програшної позиції хука.",
                            IsLibrary = true,
                            MuscleGroup = 4,
                            Name = "Задній удар",
                            NameEn = "Back Attack",
                            Style = 1,
                            Tips = "Поєднуй з ротацією корпуса. Відпрацюй повільно — деталь рятує матч."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Бічний тиск плечем уперед і вниз — основний рух прес-стилю.",
                            IsLibrary = true,
                            MuscleGroup = 4,
                            Name = "Хід короля",
                            NameEn = "King's Move",
                            Style = 2,
                            Tips = "Плече веде рух, рука лише утримує. Пресуй усім корпусом."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Натиск вниз зовнішньою частиною руки — доповнення до ходу короля.",
                            IsLibrary = true,
                            MuscleGroup = 3,
                            Name = "Тиск трицепсом",
                            NameEn = "Tricep Press",
                            Style = 2,
                            Tips = "Рука пряма, лікоть ззовні. Натискай через усю руку вниз до столу."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Тиск руки вбік від себе з опором блоку або партнера.",
                            IsLibrary = true,
                            MuscleGroup = 4,
                            Name = "Бічний тиск",
                            NameEn = "Side Pressure",
                            Style = 2,
                            Tips = "Тренуй обидві сторони рівномірно. Зміцнює позицію при пресі."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Класичне згинання зап'ястка зі штангою або гантеллю долонею вгору.",
                            IsLibrary = true,
                            MuscleGroup = 0,
                            Name = "Згинання зап'ястка",
                            NameEn = "Wrist Curl",
                            Style = 3,
                            Tips = "Повний діапазон — від повного розгинання до максимального згинання."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Згинання зап'ястка долонею вниз — розгиначі зап'ястка.",
                            IsLibrary = true,
                            MuscleGroup = 0,
                            Name = "Зворотнє згинання",
                            NameEn = "Reverse Wrist Curl",
                            Style = 3,
                            Tips = "Часто ігнорують, але критично для балансу і профілактики травм."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Підйом гантелі нейтральним хватом — плечово-променевий м'яз.",
                            IsLibrary = true,
                            MuscleGroup = 2,
                            Name = "Молотковий підйом",
                            NameEn = "Hammer Curl",
                            Style = 3,
                            Tips = "Головний рух для сили тяги. Тримай лікоть нерухомо."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Намотування ваги на ролик обертанням зап'ясток — загальна сила передпліччя.",
                            IsLibrary = true,
                            MuscleGroup = 1,
                            Name = "Ролик для зап'ястка",
                            NameEn = "Wrist Roller",
                            Style = 3,
                            Tips = "Роби обидва напрямки: намотування і розмотування."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Тяга горизонтального блоку збоку до себе — симуляція загального руху за столом.",
                            IsLibrary = true,
                            MuscleGroup = 1,
                            Name = "Тяга блоку збоку",
                            NameEn = "Cable Side Pull",
                            Style = 3,
                            Tips = "Стань боком до блоку, тягни через усю руку. Підбери висоту блоку під свій стіл."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Розгинання пальців проти опору резинки або спеціального тренажера.",
                            IsLibrary = true,
                            MuscleGroup = 1,
                            Name = "Розгинання пальців",
                            NameEn = "Finger Extension",
                            Style = 3,
                            Tips = "Баланс м'язів пальців — профілактика тендинітів і травм."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Вертикальна або горизонтальна тяга з лямкою без участі пальців — ізоляція передпліччя.",
                            IsLibrary = true,
                            MuscleGroup = 1,
                            Name = "Тяга лямкою",
                            NameEn = "Strap Pull",
                            Style = 3,
                            Tips = "Зафіксуй зап'ясток у нейтралі. Тягни тільки передпліччям."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Тяга зі штангою або блоком з упором ліктем — ізоляція ліктьового згинача.",
                            IsLibrary = true,
                            MuscleGroup = 2,
                            Name = "Ліктьова тяга",
                            NameEn = "Elbow Curl",
                            Style = 3,
                            Tips = "Рух повільний і контрольований. Критично для втримання позиції за столом."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Стискання гумового м'яча або еспандера — комплексна міцність захвату.",
                            IsLibrary = true,
                            MuscleGroup = 6,
                            Name = "Захват кулі",
                            NameEn = "Ball Grip",
                            Style = 3,
                            Tips = "Тренуй на витривалість (30+ стискань) та на максимум (3-5 сек утримання)."
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Обертання всього передпліччя з пронацією від плеча — підключення великих м'язів.",
                            IsLibrary = true,
                            MuscleGroup = 4,
                            Name = "Пронаційне обертання",
                            NameEn = "Pronation Rotation",
                            Style = 0,
                            Tips = "Рухається все передпліччя, а не лише зап'ясток. Для потужного топ-ролу."
                        });
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.Macroperiod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FocusStyle")
                        .HasColumnType("integer");

                    b.Property<int>("Goal")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeeksCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Macroperiods");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteOneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteTwoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeightCategory")
                        .HasColumnType("integer");

                    b.Property<string>("WinMethod")
                        .HasColumnType("text");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteOneId");

                    b.HasIndex("AthleteTwoId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.Mesocycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<Guid>("MacroperiodId")
                        .HasColumnType("uuid");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartWeek")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MacroperiodId");

                    b.ToTable("Mesocycles");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.TournamentParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Place")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeightCategory")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentParticipants");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.TrainingBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DayTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int?>("IntensityPercent")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Reps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DayTemplateId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("TrainingBlocks");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.TrainingExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("TrainingExercises");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccentColorsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WallpaperUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.DayTemplate", b =>
                {
                    b.HasOne("OverTheTop.Domain.Entities.Mesocycle", "Mesocycle")
                        .WithMany("DayTemplates")
                        .HasForeignKey("MesocycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesocycle");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.Macroperiod", b =>
                {
                    b.HasOne("OverTheTop.Domain.Entities.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.Match", b =>
                {
                    b.HasOne("OverTheTop.Domain.Entities.Athlete", "AthleteOne")
                        .WithMany()
                        .HasForeignKey("AthleteOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OverTheTop.Domain.Entities.Athlete", "AthleteTwo")
                        .WithMany()
                        .HasForeignKey("AthleteTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OverTheTop.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AthleteOne");

                    b.Navigation("AthleteTwo");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.Mesocycle", b =>
                {
                    b.HasOne("OverTheTop.Domain.Entities.Macroperiod", "Macroperiod")
                        .WithMany("Mesocycles")
                        .HasForeignKey("MacroperiodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macroperiod");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.TournamentParticipant", b =>
                {
                    b.HasOne("OverTheTop.Domain.Entities.Athlete", "Athlete")
                        .WithMany("TournamentParticipants")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OverTheTop.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Participants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.TrainingBlock", b =>
                {
                    b.HasOne("OverTheTop.Domain.Entities.DayTemplate", "DayTemplate")
                        .WithMany("Blocks")
                        .HasForeignKey("DayTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OverTheTop.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayTemplate");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.TrainingExercise", b =>
                {
                    b.HasOne("OverTheTop.Domain.Entities.TrainingSession", "Session")
                        .WithMany("Exercises")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.TrainingSession", b =>
                {
                    b.HasOne("OverTheTop.Domain.Entities.Athlete", "Athlete")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("OverTheTop.Domain.Entities.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.Athlete", b =>
                {
                    b.Navigation("TournamentParticipants");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.DayTemplate", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.Macroperiod", b =>
                {
                    b.Navigation("Mesocycles");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.Mesocycle", b =>
                {
                    b.Navigation("DayTemplates");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("OverTheTop.Domain.Entities.TrainingSession", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
